name: RevueHub CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, build, lint and test
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      run: |
        yarn install
        yarn build
        yarn lint
        yarn test
    # Temporarily disabled. Enable after auth integration is complete. Manual checks will be done for now
    # - name: Run Lighthouse CI (Performance, accessibility, best practises and SEO testing)
    #   env:
    #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    #   run: |
    #     yarn lhci:autorun
